import { Inter } from "next/font/google";
import "./main.css";
import HeaderTab from "@/components/HeaderTab";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Cloned Heyfood Store Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <HeaderTab />
        {children}
      </body>
    </html>
  );
}
